#ifndef SF64_ACTOR_DEBRIS_H
#define SF64_ACTOR_DEBRIS_H

typedef enum ActorDebrisType {
    ACTORDEBRIS_0,
    ACTORDEBRIS_1,
    ACTORDEBRIS_2,
    ACTORDEBRIS_3,
    ACTORDEBRIS_4,
    ACTORDEBRIS_39 = 39,
    ACTORDEBRIS_TI_GORAS,
    ACTORDEBRIS_ZO_BIRD,
    ACTORDEBRIS_ZO_ZGULL,
    ACTORDEBRIS_ZO_SHRIMP,
    ACTORDEBRIS_ZO_TROIKA,
    ACTORDEBRIS_45,
    ACTORDEBRIS_TI_RASCO,
    ACTORDEBRIS_47,
    ACTORDEBRIS_48,
    ACTORDEBRIS_49,
    ACTORDEBRIS_50,
    ACTORDEBRIS_51,
    ACTORDEBRIS_52,
    ACTORDEBRIS_53,
    ACTORDEBRIS_54,
    ACTORDEBRIS_55,
    ACTORDEBRIS_56,
    ACTORDEBRIS_57,
    ACTORDEBRIS_58,
    ACTORDEBRIS_59,
    ACTORDEBRIS_70 = 70,
} ActorDebrisType;

#endif
